### ISSUE TITLE
Need more flexible support of release naming

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/genesis-index#3]
The `etcd` BOSH release builds its tarballs as `etcd-release-{{version}}.tgz` As a result, genesis-indexer needs the name to be etcd-release. However when using it in a repo, we need to use the name `etcd` instead of `etcd-release`. Do we need to update the indexer and/or genesis itself to compensate for this somehow, or am I hopefully just unaware of a feature that allows this?

**Comment by jhunt** [comment]
I believe this is/was already supported.
