### ISSUE TITLE
sha1 missmatch

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis-index#5]
it appears sha1 is sometimes not determined correctly or is out of sync with how the bosh-director determins sha1.
see here:  https://ci.vsphere.starkandwayne.com/pipelines/dingo-postgresql-deployments/jobs/bosh-lite-try-anything/builds/83

**Comment by bodymindarts** [comment]
Re-running https://ci.vsphere.starkandwayne.com/pipelines/genesis-index/jobs/dingo-postgresql changed the sha1 to the correct sha1. Looks like the job was initially triggered _before_ the complete release was uploaded and available on github, so that the first sha1 that was stored was from a partially downloaded release.

**Comment by jhunt** [comment]
Is this still a problem?
