### ISSUE TITLE
Pipeline not picking up latest stemcell for bosh-aws-xen-hvm-ubuntu-trusty-go_agent

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/genesis-index#8]
Overnight a new stemcell v3263.8 was released, triggering genesis. All environments failed because the stemcell wasn't uploaded by bosh correctly. Turns out that genesis-index doesn't know about the latest release and couldn't provide the correct URL.

https://ci.vsphere.starkandwayne.com/teams/main/pipelines/genesis-index/jobs/bosh-aws-xen-hvm-ubuntu-trusty-go_agent/builds/21

I have manually used `indexer` to add the aws stemcell to move on but the root cause for the pipeline not picking it up still needs to be investigated.

**Comment by jhunt** [comment]
These are all green now, so I'm going to close this issue.

![screen shot 2017-02-24 at 12 32 59 pm](https://cloud.githubusercontent.com/assets/20047/23313860/6e057894-fa8d-11e6-92e4-33e743f71025.png)
